#include <stdio.h>
#include <stdlib.h>
#include <assert.h>

#include "img_io.h"
#include "sift.h"

// Octaves generated by down sampling
// Careful, this memory allocation is far from optimal.
// All octaves are given the same size as the original image
// octavesW_g[i] * octavesH_g[i] is the actual memory necessary for octave i
unsigned char octaves_g[MAX_O][MAX_OCTAVE_SIZE];

// difference of gaussians: equivalent with dynamic allocation
/*for(i = 0; i < NUMBER_OF_OCTAVES; i++){
    for(j = 0; j < NUMBER_OF_SCALES-1; j++){
        dog[i][j] =
            (float*)malloc( octavesW_g[i] * octavesH_g[i] * sizeof(float));
    }
}*/

/* Octaves: equivalent with dynamic allocation
 for(i = 0; i < NUMBER_OF_OCTAVES; i++){
     octaves[i] = (unsigned char*)
         malloc(octavesW[i] * octavesH[i] * sizeof(unsigned char));
 }*/

// scale space
float scaleSpace_g[MAX_O][MAX_S][MAX_OCTAVE_SIZE];

// scale space: equivalent with dynamic allocation
/*for(i = 0; i < NUMBER_OF_OCTAVES; i++){
    for(j = 0; j < NUMBER_OF_SCALES; j++){
        scaleSpace[i][j] =
            (float*)malloc(octavesW_g[i] * octavesH_g[i] * sizeof(float));
    }
}*/

// difference of gaussians
float dog_g[MAX_O][MAX_S-1][MAX_OCTAVE_SIZE];

// width of each octave
int octavesW_g[MAX_O];
// height of each octave
int octavesH_g[MAX_O];

// extreme points
pointList keyPointList_g;

int
main(int argc, char* argv[]) {
    int w, h, i;
    unsigned char* in_img;


    in_img = read_pgm(&w, &h, "akiyo1.pgm");

    if (w != 352 || h != 288) {
        fprintf(
            stderr,
            "Only CIF pictures are supported\n");
        exit(1);
    }

    assert(in_img != NULL);

    // computing the width of octaves at each level
    octavesW_g[0] = w;
    for(i = 1; i < NUMBER_OF_OCTAVES; i++){
        octavesW_g[i] = octavesW_g[i-1]/2;
    }
    // computing the height of octaves at each level
    octavesH_g[0] = h;
    for(i = 1; i < NUMBER_OF_OCTAVES; i++){
        octavesH_g[i] = octavesH_g[i-1]/2;
    }

    // Setting the original number of detected points to 0
    keyPointList_g.size = 0;

    sift(in_img, w, h, "Resultat.pgm", octaves_g, octavesW_g,
            octavesH_g, scaleSpace_g, dog_g, &keyPointList_g,
            NUMBER_OF_OCTAVES, NUMBER_OF_SCALES);

    return 0;
}// main()

